version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: darkhasti-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: darkhasti
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_SERVER_PASSWORD}
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

volumes:
  redis_data: